# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  context-switch-xplr = {
    pname = "context-switch-xplr";
    version = "85ac284b33144540741f48a5a42d3366d00acae9";
    src = fetchFromGitHub {
      owner = "igorepst";
      repo = "context-switch.xplr";
      rev = "85ac284b33144540741f48a5a42d3366d00acae9";
      fetchSubmodules = false;
      sha256 = "sha256-ryVvZIMBkG7FpJVpEj0SfibWFDEEsvA8089ptErlqwg=";
    };
    date = "2023-12-28";
  };
  dragon-xplr = {
    pname = "dragon-xplr";
    version = "5fbddcb33f7d75a5abd12d27223ac55589863335";
    src = fetchFromGitHub {
      owner = "sayanarijit";
      repo = "dragon.xplr";
      rev = "5fbddcb33f7d75a5abd12d27223ac55589863335";
      fetchSubmodules = false;
      sha256 = "sha256-FJbyu5kK78XiTJl0NNXcI0KPOdXOPwpbBCWPUEpu5zA=";
    };
    date = "2023-01-11";
  };
  dua-cli-xplr = {
    pname = "dua-cli-xplr";
    version = "66ccf983fab7f67d6b00adc0365a2b26550e7f81";
    src = fetchFromGitHub {
      owner = "sayanarijit";
      repo = "dua-cli.xplr";
      rev = "66ccf983fab7f67d6b00adc0365a2b26550e7f81";
      fetchSubmodules = false;
      sha256 = "sha256-XDhXaS8GuY3fuiSEL0WcLFilZ72emmjTVi07kv5c8n8=";
    };
    date = "2022-01-19";
  };
  extra-icons-xplr = {
    pname = "extra-icons-xplr";
    version = "1f27b9a74c23b869fe64d12f3d8c2a1207ff8eb7";
    src = fetchFromGitHub {
      owner = "dtomvan";
      repo = "extra-icons.xplr";
      rev = "1f27b9a74c23b869fe64d12f3d8c2a1207ff8eb7";
      fetchSubmodules = false;
      sha256 = "sha256-9xDK960CSqdHdKKczH5ULpS0s/2KYwl+NgvQCt6FLCs=";
    };
    date = "2023-06-01";
  };
  fzf-xplr = {
    pname = "fzf-xplr";
    version = "c8991f92946a7c8177d7f82ed939d845746ebaf5";
    src = fetchFromGitHub {
      owner = "sayanarijit";
      repo = "fzf.xplr";
      rev = "c8991f92946a7c8177d7f82ed939d845746ebaf5";
      fetchSubmodules = false;
      sha256 = "sha256-dpnta67p3fYEO3/GdvFlqzdyiMaJ9WbsnNmoIRHweMI=";
    };
    date = "2023-09-04";
  };
  icons-xplr = {
    pname = "icons-xplr";
    version = "6133ea79c41629591c72fa4c51132f7a3cb30782";
    src = fetchFromGitHub {
      owner = "prncss-xyz";
      repo = "icons.xplr";
      rev = "6133ea79c41629591c72fa4c51132f7a3cb30782";
      fetchSubmodules = false;
      sha256 = "sha256-RqSHqLVLZ0hrP6RLHgNtReoy6pW/nzxestwLdugFro0=";
    };
    date = "2022-05-08";
  };
  offline-docs-xplr = {
    pname = "offline-docs-xplr";
    version = "cba060b5a009696fe1b2ccbdd73d7ba2e2d7b51d";
    src = fetchFromGitHub {
      owner = "sayanarijit";
      repo = "offline-docs.xplr";
      rev = "cba060b5a009696fe1b2ccbdd73d7ba2e2d7b51d";
      fetchSubmodules = false;
      sha256 = "sha256-+ilunEbnPpP8NEhfNlr8rK7fwQhyTHFhsFZnI85TkXk=";
    };
    date = "2024-02-10";
  };
  ouch-xplr = {
    pname = "ouch-xplr";
    version = "375edf19ff3e0286bd7a101b9e4dd24fa5abaeb8";
    src = fetchFromGitHub {
      owner = "dtomvan";
      repo = "ouch.xplr";
      rev = "375edf19ff3e0286bd7a101b9e4dd24fa5abaeb8";
      fetchSubmodules = false;
      sha256 = "sha256-YGFQKzIYIlL+UW2Nel2Tw7WC3MESaVbWYlpj5o2FfLs=";
    };
    date = "2022-01-23";
  };
  scp-xplr = {
    pname = "scp-xplr";
    version = "578bfd6bd379b113ce63bb0f73658eef2594c817";
    src = fetchFromGitHub {
      owner = "sayanarijit";
      repo = "scp.xplr";
      rev = "578bfd6bd379b113ce63bb0f73658eef2594c817";
      fetchSubmodules = false;
      sha256 = "sha256-E/a1JQX7cKOWpPcEFvew3LDLTCyHwXfbTNDtNw2WiXY=";
    };
    date = "2024-02-10";
  };
  style-xplr = {
    pname = "style-xplr";
    version = "e1fbd803e8a1dc4a6a1460816b485fb06412e6b8";
    src = fetchFromGitHub {
      owner = "emsquid";
      repo = "style.xplr";
      rev = "e1fbd803e8a1dc4a6a1460816b485fb06412e6b8";
      fetchSubmodules = false;
      sha256 = "sha256-eP0+xA3qtbAUJaqBxdY1qDhnCF/tY3MAaq1fZd4SLmA=";
    };
    date = "2023-01-09";
  };
  tri-pane-xplr = {
    pname = "tri-pane-xplr";
    version = "d90c65eb2bdd182f09db2db8969a99666f90c78b";
    src = fetchFromGitHub {
      owner = "sayanarijit";
      repo = "tri-pane.xplr";
      rev = "d90c65eb2bdd182f09db2db8969a99666f90c78b";
      fetchSubmodules = false;
      sha256 = "sha256-repzWTUYZirpBwQ+SEe1Gp1EFMHGG5VONSRS00c995c=";
    };
    date = "2023-07-05";
  };
  type-to-nav-xplr = {
    pname = "type-to-nav-xplr";
    version = "de817bd19c56b7cbb1c39c05e4412b7f188b548c";
    src = fetchFromGitHub {
      owner = "sayanarijit";
      repo = "type-to-nav.xplr";
      rev = "de817bd19c56b7cbb1c39c05e4412b7f188b548c";
      fetchSubmodules = false;
      sha256 = "sha256-BBIGX0gLJeX3F0wn22IGUr/qzlL4ryh0RjsZURJ1xq4=";
    };
    date = "2022-01-19";
  };
  wl-clipboard-xplr = {
    pname = "wl-clipboard-xplr";
    version = "a3ffc87460c5c7f560bffea689487ae14b36d9c3";
    src = fetchFromGitHub {
      owner = "sayanarijit";
      repo = "wl-clipboard.xplr";
      rev = "a3ffc87460c5c7f560bffea689487ae14b36d9c3";
      fetchSubmodules = false;
      sha256 = "sha256-I4rh5Zks9hiXozBiPDuRdHwW5I7ppzEpQNtirY0Lcks=";
    };
    date = "2023-01-11";
  };
  xclip-xplr = {
    pname = "xclip-xplr";
    version = "ddbcce2a255537ce8e3680575bbe964b49d05979";
    src = fetchFromGitHub {
      owner = "sayanarijit";
      repo = "xclip.xplr";
      rev = "ddbcce2a255537ce8e3680575bbe964b49d05979";
      fetchSubmodules = false;
      sha256 = "sha256-9WYT52H6vfqTGos57/Um/UqVCkteTAbnUSQ5xDb+JrY=";
    };
    date = "2023-01-11";
  };
  zoxide-xplr = {
    pname = "zoxide-xplr";
    version = "e50fd35db5c05e750a74c8f54761922464c1ad5f";
    src = fetchFromGitHub {
      owner = "sayanarijit";
      repo = "zoxide.xplr";
      rev = "e50fd35db5c05e750a74c8f54761922464c1ad5f";
      fetchSubmodules = false;
      sha256 = "sha256-ZiOupn9Vq/czXI3JHvXUlAvAFdXrwoO3NqjjiCZXRnY=";
    };
    date = "2023-01-11";
  };
}
